### ISSUE TITLE
入部フローの確立

### ISSUE THREAD

**Issue by manattan** [HUITGroup/agenda-core#4]
- discordに招待するだけ？？
- 年会費を受け取らないとdiscordには入れない？役割の設定のみで、お金もらわなくてもdiscord入れちゃていいのか?

**Comment by takapiro99** [comment]
部費払わなくてもとりあえずディスコにいれて、いちばん下の権限は軽いチャンネルの閲覧権限のみって感じにすればいいのではないでしょうか

**Comment by takapiro99** [comment]
一週間は試用期間で色んなチャンネルを見れるようにしたらHUITのことを知ってもらえていいかなって思ったけど、オペレーションが増えてしんどそうなので後からでいいかなと思いました。

**Comment by takapiro99** [comment]
部費を取り始めたら名前は管理しなきゃいけないけど、今は特に何も(googleフォームとか)せず 入れてしまっていいのではないかと思いました。

ただ自己紹介チャンネルはあったほうがいいのかな？
